Handle otpauth:// URIs
X1nto/Mauth pull request #28
Opened 2022-12-31 17:52 UTC by YavaCoco

* This feature is useful when a otp QR code is scanned from another App
* Make getDigestFromUriAlgorithm case insensitive

2022-12-31 19:11 UTC, X1nto commented on app/src/main/java/com/xinto/mauth/MainActivity.kt
> +            accountToAdd = when (val result = parser.parseOtpUri(intent?.dataString!!)) {
It's better to move this functionality to a ViewModel IMO

2022-12-31 19:13 UTC, X1nto commented on app/src/main/java/com/xinto/mauth/MainActivity.kt
> +                        if(showErrorDialog.value)
Please follow the code formatting properly.
```suggestion
                        if (showErrorDialog.value)
```

2022-12-31 19:14 UTC, X1nto requested changes

2022-12-31 19:14 UTC, X1nto commented on app/src/main/java/com/xinto/mauth/MainActivity.kt
> +                        val showErrorDialog = remember { mutableStateOf(true) }
This could be changed to use the State delegate
```suggestion
                        var showErrorDialog by remember { mutableStateOf(true) }
```

2022-12-31 19:15 UTC, X1nto commented on app/src/main/java/com/xinto/mauth/MainActivity.kt
> +                        val showErrorDialog = remember { mutableStateOf(true) }
Update the `.value` calls respectively

2023-01-01 11:17 UTC, YavaCoco commented
This also creates a problem whenever onCreate() is called a second time, for example when the screen is rotated, the add account screen is displayed again.

2023-01-13 14:33 UTC, X1nto commented
Closing in favor of #30

2023-01-13 14:33 UTC, closed without merging