feat: otp uri
X1nto/Mauth pull request #30
Opened 2023-01-12 22:28 UTC by Lastaapps

Hi,

I had to implement a TOTP mfa in my Android app and found out, that this perfect app does not support opening `otpauth` URI scheme from another app (other authenticators do). So I implemented this nice little feature.

I am sorry if I should ask you before. This is my first time contributing to a foreign project.

Thanks for the project

Have a nice day

2023-01-12 22:30 UTC, Lastaapps commented
Ok, I see someone has already done it, nevermind 😅

2023-01-13 09:03 UTC, X1nto commented
I might merge this one instead of the author of the previous PR doesn't follow the required changes I listed. This one actually utilizes the ViewModel so I actually prefer it over the previous one

2023-01-13 09:05 UTC, X1nto commented on app/src/main/java/com/xinto/mauth/ui/viewmodel/MainViewModel.kt
> +    private val _optUri = MutableStateFlow<DomainAccountInfo?>(null)
Could use Compose State instead, but not really a deal breaker.

2023-01-13 09:07 UTC, X1nto requested changes

2023-01-13 09:07 UTC, X1nto commented on README.md
> +  - [x] Key Uri (otpauth)
"Deeplinks" sounds more intuitive to a regular user IMO
```suggestion
  - [x] Deeplinks
```

2023-01-13 10:13 UTC, X1nto commented on app/src/main/java/com/xinto/mauth/ui/viewmodel/MainViewModel.kt
> +    private val _optUri = mutableStateOf<DomainAccountInfo?>(null)
```suggestion
    var optUri = mutableStateOf<DomainAccountInfo?>(null)
        private set
``` is more readable since one variable now does both things. update the .value calls accordingly (`otpUri.value = something` becomes `otpUri = something`

2023-01-13 10:14 UTC, X1nto requested changes
just one thing left, otherwise LGTM!

2023-01-13 14:29 UTC, X1nto approved these changes
LGTM!

2023-01-13 14:35 UTC, X1nto commented
I'll fix the build msyelf

2023-01-13 14:35 UTC, Lastaapps commented
Oh fuck, I really love these kinds of fixes when you want to update something small, don't check it and you break it instead, I'll fix it now

2023-01-13 17:35 UTC, X1nto approved these changes

2023-01-13 18:14 UTC, merged

2023-01-13 18:14 UTC, X1nto commented
Thank you for your contribution!

2023-01-13 18:49 UTC, Lastaapps commented
You're welcome, thanks for your project.